# Rscript to apply the best model from the paper to an arbitrary feature
#     set generated by 
# SIEVEFeatures.py -f [fasta file] -o [output base] -m simple -k 14 -M reduced_alphabet_0

# source the code to do this
source("SIEVEUb.R")

# script to run SIEVEUb on example data
main = function(feature_table_fname) {
  # To generate features from a fasta file use the following command
  #    from the SIEVEServer code
  # SIEVEFeatures.py -f [fasta file] -o [output base] -m gist -s k:14:::reduced_alphabet_0
  
  # read in the best model for ubiquitin ligase prediction from the paper
  load("data/SIEVEUb_best_model.Rdata")
  
  cat("Header...\n")
  
  #get the input feature file
  these_features = read.table(feature_table_fname, sep="\t", row.names=1, header=1, stringsAsFactors=F)
  
  results = validate_svm(train_model=sieveub_best_model, test_data=t(these_features))
  
  predictions = results$predictions
  predictions = predictions[order(predictions[,1]),]
  
  # output predictions as text
  cat("#id\tnegative prob\tpositive prob\n")
  for (i in 1:nrow(results$predictions)) {
    cat(rownames(predictions)[i], predictions[i,1], predictions[i,2], "\n", sep="\t")
  }
} 

these_args = commandArgs()
cat("Input...\n")
filename <- these_args[6]
main(filename)
